### ISSUE TITLE
exception for signal "updated" Error: Type name xxx is already registered

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#106]
Hi,

from time to time the gnome-shell extension disappears from the top-right menu.
I get many of these in the logs:
```
oct. 25 22:07:43 imac gnome-session[2910]: (gnome-shell:3042): Gjs-WARNING **: JS ERROR: Exception in callback for signal: updated: Error: Type name Gjs_GPasteAboutItem is already registered
oct. 25 22:07:43 imac gnome-session[2910]: GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
oct. 25 22:07:43 imac gnome-session[2910]: Class@resource:///org/gnome/gjs/modules/lang.js:152
oct. 25 22:07:43 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js:29
oct. 25 22:07:43 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:36
oct. 25 22:07:43 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js:28
oct. 25 22:07:43 imac gnome-session[2910]: initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
oct. 25 22:07:43 imac gnome-session[2910]: enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:109
oct. 25 22:07:43 imac gnome-session[2910]: enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:311
oct. 25 22:07:43 imac gnome-session[2910]: enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:310
oct. 25 22:07:43 imac gnome-session[2910]: _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
oct. 25 22:07:43 imac gnome-session[2910]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
oct. 25 22:07:43 imac gnome-session[2910]: SessionMode<._sync@resource:///org/gnome/shell/ui/sessionMode.js:205
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: SessionMode<.popMode@resource:///org/gnome/shell/ui/sessionMode.js:174
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: ScreenShield<._continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1215
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: ScreenShield<.deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1200
oct. 25 22:07:43 imac gnome-session[2910]: AuthPrompt<.finish@resource:///org/gnome/shell/gdm/authPrompt.js:490
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: UnlockDialog<.finish@resource:///org/gnome/shell/ui/unlockDialog.js:147
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: ScreenShield<.deactivate@resource:///org/gnome/shell/ui/screenShield.js:1199
oct. 25 22:07:43 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 25 22:07:43 imac gnome-session[2910]: ScreenShield<._init/</<@resource:///org/gnome/shell/ui/screenShield.js:561
oct. 25 22:07:43 imac gnome-session[2910]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
oct. 25 22:07:43 imac gnome-session[2910]: _convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:129

```

or this
```
oct. 24 17:52:13 imac gnome-session[2910]: (gnome-shell:3042): GLib-GObject-WARNING **: /build/glib2.0-dt6trg/glib2.0-2.42.0/./gobject/gsignal.c:2579: instance '0x5624130' has no handler with id '4382566'
oct. 24 17:52:13 imac gnome-session[2910]: (gnome-shell:3042): Gjs-WARNING **: JS ERROR: Error: Type name Gjs_GPasteAboutItem is already registered
oct. 24 17:52:13 imac gnome-session[2910]: GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
oct. 24 17:52:13 imac gnome-session[2910]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
oct. 24 17:52:13 imac gnome-session[2910]: Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
oct. 24 17:52:13 imac gnome-session[2910]: Class@resource:///org/gnome/gjs/modules/lang.js:152
oct. 24 17:52:13 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js:29
oct. 24 17:52:13 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:36
oct. 24 17:52:13 imac gnome-session[2910]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js:28
oct. 24 17:52:13 imac gnome-session[2910]: initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
oct. 24 17:52:13 imac gnome-session[2910]: enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:109
oct. 24 17:52:13 imac gnome-session[2910]: _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:284
oct. 24 17:52:13 imac gnome-session[2910]: _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:283
```

**Comment by Keruspe** [comment]
Is this bug still valid?

If so, what versions of gnome-shell gjs and GPaste are you using?

**Comment by Keruspe** [comment]
Finally managed to track it down, will release a fix this week end.

see 0e899af538631026c6cd739986ea854f79b91c95

**Comment by mvuets** [comment]
@Keruspe++ You are amazing!

**Comment by kapouer** [comment]
yes, hopefully this will get accepted into debian/jessie. May i take only https://github.com/Keruspe/GPaste/commit/0e899af538631026c6cd739986ea854f79b91c95 ?

**Comment by Keruspe** [comment]
@kapouer This commit should suffice yep.

As of writing, I'm releasing 3.14.2 though, if relevant.

**Comment by kapouer** [comment]
The whole release couldn't go to debian/jessie, but i managed to get the commit accepted. Extension doesn't disappear anymore, thank you !

**Comment by MaximKraev** [comment]
Still have that issue, shell 3.16.2, GPaste 3.16.2.1
```
Jun 19 13:20:07 archi gnome-session[815]: (gnome-shell:10723): Gjs-WARNING **: JS ERROR: Error: Type name Gjs_GPasteAboutItem is already registered
Jun 19 13:20:07 archi gnome-session[815]: GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
Jun 19 13:20:07 archi gnome-session[815]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Jun 19 13:20:07 archi gnome-session[815]: Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
Jun 19 13:20:07 archi gnome-session[815]: Class@resource:///org/gnome/gjs/modules/lang.js:152
Jun 19 13:20:07 archi gnome-session[815]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js:29
Jun 19 13:20:07 archi gnome-session[815]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:36
Jun 19 13:20:07 archi gnome-session[815]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js:28
Jun 19 13:20:07 archi gnome-session[815]: initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
Jun 19 13:20:07 archi gnome-session[815]: enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:109
Jun 19 13:20:07 archi gnome-session[815]: _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:284
Jun 19 13:20:07 archi gnome-session[815]: _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:283
```

**Comment by Keruspe** [comment]
Which version of gjs are you running?

**Comment by MaximKraev** [comment]
1.43.3

**Comment by Keruspe** [comment]
Can you reproduce it easily? Which action triggers it?

**Comment by MaximKraev** [comment]
didn't found exact steps to reproduce yet, but happen often, usually with some notification popup appear

**Comment by Keruspe** [comment]
Ok, I can reproduce the issue on demand now, by changing the disable-extension-version-validation dconf key

**Comment by MaximKraev** [comment]
yes I had it enabled, disabled not, checking... thank you

**Comment by Keruspe** [comment]
Well, the fact that it's enabled is not a problem, but the problem occurs when its value chages

**Comment by MaximKraev** [comment]
still the problem
http://paste.pound-python.org/show/9zgJx9WKHU73OWZkb0w7/

```
ᐅ gsettings get org.gnome.shell disable-extension-version-validation
false
```
I did reset the value, and reboot.

**Comment by Keruspe** [comment]
What's *really* weird then is that onVersionValidationChanged (from gnome-shell) which triggers this is only ever supposed to be ran when the value of the setting change.

**Comment by MaximKraev** [comment]
I do not do that. I've added a monitor to check that setting be modified.

**Comment by Keruspe** [comment]
I just made a minimal reproducer here: https://github.com/Keruspe/gnome-shell-extension-bug
Will ask gnome-shell folks if it's not a bug on their side, as you can see the code here is really pretty simple

**Comment by MaximKraev** [comment]
ok. thank you

**Comment by Keruspe** [comment]
12:12:12   #gnome-shell       halfline | keruspe: i don't know for sure, but I suspect you may be hitting a limitation of the type system   
12:12:39   #gnome-shell       halfline | instead of making BugItem be a St.Button, make it have a St.Button and see if that helps                         
12:13:25   #gnome-shell       halfline | it's idiomatic to have this.actor = new St.Button() and then add bugItem.actor to the container

**Comment by Keruspe** [comment]
That seem to do the trick, will try to get to it by next week but not sure if I'll be able to

**Comment by Keruspe** [comment]
Actually, this is now fixed in the gpaste-3.16 and master branches.

**Comment by MaximKraev** [comment]
looks fixed, don't have that exception anymore, thank you.

**Comment by MaximKraev** [comment]
now works better, doesn't stop other extensions, but still fails with 
```

Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: TypeError: this._client is undefined
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: Error: Extension point conflict: there is already a status indicator for role gpaste
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: TypeError: this._client is undefined
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: Error: Extension point conflict: there is already a status indicator for role gpaste
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: TypeError: this._client is undefined
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: Error: Extension point conflict: there is already a status indicator for role gpaste
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: TypeError: this._client is undefined
Jun 20 12:45:00 archi gnome-session[834]: Gjs-Message: JS LOG: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: Error: Extension point conflict: there is already a status indicator for role gpaste
```
after if I press the hotkey to show the applet, 2 applets appears (on left and right side of the screen)

**Comment by Keruspe** [comment]
Do you have a way to reproduce? I cannot seem to reproduce this one

**Comment by Keruspe** [comment]
(thanks a lot for digging all this out, btw, much appreciated)

**Comment by MaximKraev** [comment]
looks like it is failing after a notification from a QT app (or possibly GTK app also), I have geary and Cutegram working, sometimes after a notification (new message) is shown I have that problem, looks like a possible gnome shell bug.

**Comment by Keruspe** [comment]
If you find a notification that is easy to trigger and reliably causes this I would be greatly interested

**Comment by MaximKraev** [comment]
Currently Cutegram notifications reproduces the problem often, trying to find/write a minimal program to do that, notification thought python and notify-send works fine, looks like the issue appears in the same time as https://bugzilla.gnome.org/show_bug.cgi?id=749656

**Comment by Keruspe** [comment]
Everything in GPaste is async, so if gnome-shell does one tiny thing synchronously and then expect other things not to have changed, it could cause some race conditions inside of gnome-shell yep.

I'll be off for a few days quite soon, but will look at it asap once I can reproduce

**Comment by MaximKraev** [comment]
as soon as I disabled gpaste extension there are no "Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed" errors in the log anymore, I found this https://github.com/xtranophilist/gnome-shell-extension-sensors/issues/83 by googing, may be you can find an idea from that thread.

**Comment by Keruspe** [comment]
I just pushed a few changes which may or may not fix your issues (especially the clutter text one)

**Comment by Keruspe** [comment]
@MaximKraev did you have the occasion to try the last changes?

Please open a new issue if the problem persists, as it no longer is related to this issue at all.
